In [1]:
from keras.models import load_model
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.utils import to_categorical

Using TensorFlow backend.


In [2]:
# Read in the full dataset that was cleaned
data = pd.read_csv('cleandataformodel.csv')
data = data.drop('Unnamed: 0', axis=1)

In [3]:
# prep the data to test 
X = data.drop("Loan_Status", axis=1)
y = data["Loan_Status"]
print(X.shape, y.shape)

(614, 10) (614,)


In [4]:
data.head()

Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0        0           0          1              0             5849   
1        1           1          1              0             4583   
2        1           0          1              1             3000   
3        1           0          0              0             2583   
4        0           0          1              0             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0  146.412162             360.0             1.0   
1             1508.0  128.000000             360.0             1.0   
2                0.0   66.000000             360.0             1.0   
3             2358.0  120.000000             360.0             1.0   
4                0.0  141.000000             360.0             1.0   

   Property_Area  Loan_Status  
0              0            1  
1              2            0  
2              0            1  
3              0            1  
4              0            1

In [5]:
#load the saved scaler and scale the full test data
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.utils import to_categorical
from sklearn.externals import joblib

model_scaler = joblib.load('model_scaler.pkl')
X_scaled = model_scaler.transform(X)

# Step 1: Label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(y)
encoded_y = label_encoder.transform(y)

# Step 2: Convert encoded labels to one-hot-encoding
y_categorical = to_categorical(encoded_y)

In [6]:
#load the model
model = load_model("mortgage_model_trained.h5")

In [7]:
# test
model_loss, model_accuracy = model.evaluate(X_scaled, y_categorical, verbose=2)
print(f"Normal Neural Network with data - Loss: {model_loss}, Accuracy: {model_accuracy}")


Normal Neural Network with data - Loss: 0.37520376910798325, Accuracy: 0.8501628664495114


In [8]:
# predictions from the data
predictions = model.predict_classes(X_scaled)
predictions

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0,

In [9]:
# classification report from the test
from sklearn.metrics import classification_report
print(classification_report(y, predictions))


             precision    recall  f1-score   support

          0       0.93      0.56      0.70       192
          1       0.83      0.98      0.90       422

avg / total       0.86      0.85      0.84       614



In [10]:
# test with a new small set of data, only 7 lines
test = pd.read_csv('test2.csv')
test = test.drop('Unnamed: 0', axis=1)

In [11]:
user_input = test.drop("Loan_Status", axis=1)
answers = test["Loan_Status"]
print(user_input.shape, answers.shape)

(7, 10) (7,)


In [12]:
user_input_scaled = model_scaler.transform(user_input)
label_encoder.fit(answers)
encoded_answers = label_encoder.transform(answers)
answers_categorical = to_categorical(encoded_answers)

In [13]:
test_loss, test_accuracy = model.evaluate(user_input_scaled, answers_categorical, verbose=2)
print(f"Normal Neural Network with data - Loss: {model_loss}, Accuracy: {model_accuracy}")


Normal Neural Network with data - Loss: 0.37520376910798325, Accuracy: 0.8501628664495114


In [14]:
test_predictions = model.predict_classes(user_input_scaled)
test_predictions

array([0, 1, 0, 1, 1, 1, 0], dtype=int64)

In [15]:
print(classification_report(answers, test_predictions))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00         3
          1       1.00      1.00      1.00         4

avg / total       1.00      1.00      1.00         7



In [28]:
# set the input variables from scratch
married = 1
dependents = 2
education = 1
self_employed = 0
applicantincome = 9000
coapplicantincome = 0
loanamount = 250.00
loan_amount_term = 180
credit_history = 1
property_area = 2

In [29]:
#  load the input data into a dataframe
forminput = pd.DataFrame()
forminput['Married']=[married]
forminput['Dependents']=[dependents]
forminput['Education']=[education]
forminput['Self_Employed']=[self_employed]
forminput['ApplicantIncome']=[applicantincome]
forminput['CoapplicantIncome']=[coapplicantincome]
forminput['LoanAmount']=[loanamount]
forminput['Loan_Amount_Term']=[loan_amount_term]
forminput['Credit_History']=[credit_history]
forminput['Property_Area']=[property_area]

In [30]:
forminput

Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0        1           2          1              0             9000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0       250.0               180               1   

   Property_Area  
0              2

In [31]:
#scale the input 
forminput_scaled = model_scaler.transform(forminput)

In [32]:
forminput_scaled

array([[ 0.71287918,  1.20613383,  0.51693097, -0.41649656,  0.61497735,
        -0.51620901,  1.30408535, -2.35720832,  0.4518722 ,  1.33332861]])

In [33]:
predic = model.predict_classes(forminput_scaled)
predic[0]

1