In [1]:
import numpy as np
import pandas as pd
import pickle 
from sklearn.externals import joblib

In [2]:
datawith = pd.read_csv('CleanTrainData.csv')
datawith.loc[datawith['Married']=="Yes",'Married']=1
datawith.loc[datawith['Married']=='No','Married']=0
datawith.loc[datawith['Education']=="Graduate",'Education']=1
datawith.loc[datawith['Education']=='Not Graduate','Education']=0
datawith.loc[datawith['Self_Employed']=="Yes",'Self_Employed']=1
datawith.loc[datawith['Self_Employed']=='No','Self_Employed']=0
datawith.loc[datawith['Property_Area']=="Urban",'Property_Area']=0
datawith.loc[datawith['Property_Area']=='Semiurban','Property_Area']=1
datawith.loc[datawith['Property_Area']=='Rural', 'Property_Area']=2
datawith = datawith.drop('Unnamed: 0', axis=1)
datawith.to_csv('cleandataformodel.csv')
datawith.head()

Married  Dependents Education Self_Employed  ApplicantIncome  \
0       0           0         1             0             5849   
1       1           1         1             0             4583   
2       1           0         1             1             3000   
3       1           0         0             0             2583   
4       0           0         1             0             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0  146.412162               360               1   
1             1508.0  128.000000               360               1   
2                0.0   66.000000               360               1   
3             2358.0  120.000000               360               1   
4                0.0  141.000000               360               1   

  Property_Area  Loan_Status  
0             0            1  
1             2            0  
2             0            1  
3             0            1  
4             0            1

In [3]:
X = datawith.drop("Loan_Status", axis=1)
y = datawith["Loan_Status"]
print(X.shape, y.shape)

(614, 10) (614,)


In [4]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.utils import to_categorical

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)
X_scaler = StandardScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

# Step 2: Convert labels to one-hot-encoding
y_train_categorical = to_categorical(y_train)
y_test_categorical = to_categorical(y_test)

C:\Users\Prakash\Anaconda\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [5]:
# Support vector machine linear classifier
# Fit to the training data and validate with the training label data
from sklearn.svm import SVC 
SVMmodel = SVC(kernel='sigmoid') # SVM sigmoid Model

In [6]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    "C": [1, 5, 10, 50],
    "gamma": [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5]
}

grid = GridSearchCV(SVMmodel, param_grid, verbose=3)
grid.fit(X_train_scaled, y_train)

Fitting 3 folds for each of 32 candidates, totalling 96 fits
[CV] C=1, gamma=0.0001 ...............................................
[CV] ...... C=1, gamma=0.0001, score=0.6883116883116883, total=   0.0s
[CV] C=1, gamma=0.0001 ...............................................
[CV] ...... C=1, gamma=0.0001, score=0.6862745098039216, total=   0.0s
[CV] C=1, gamma=0.0001 ...............................................
[CV] ...... C=1, gamma=0.0001, score=0.6862745098039216, total=   0.0s
[CV] C=1, gamma=0.0005 ...............................................
[CV] ...... C=1, gamma=0.0005, score=0.6883116883116883, total=   0.0s
[CV] C=1, gamma=0.0005 ...............................................
[CV] ...... C=1, gamma=0.0005, score=0.6862745098039216, total=   0.0s
[CV] C=1, gamma=0.0005 ...............................................
[CV] ...... C=1, gamma=0.0005, score=0.6862745098039216, total=   0.0s
[CV] C=1, gamma=0.001 ................................................
[CV] ....... C=1

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s


[CV] ......... C=1, gamma=0.5, score=0.7581699346405228, total=   0.0s
[CV] C=1, gamma=0.5 ..................................................
[CV] ......... C=1, gamma=0.5, score=0.7254901960784313, total=   0.0s
[CV] C=5, gamma=0.0001 ...............................................
[CV] ...... C=5, gamma=0.0001, score=0.6883116883116883, total=   0.0s
[CV] C=5, gamma=0.0001 ...............................................
[CV] ...... C=5, gamma=0.0001, score=0.6862745098039216, total=   0.0s
[CV] C=5, gamma=0.0001 ...............................................
[CV] ...... C=5, gamma=0.0001, score=0.6862745098039216, total=   0.0s
[CV] C=5, gamma=0.0005 ...............................................
[CV] ...... C=5, gamma=0.0005, score=0.6883116883116883, total=   0.0s
[CV] C=5, gamma=0.0005 ...............................................
[CV] ...... C=5, gamma=0.0005, score=0.6862745098039216, total=   0.0s
[CV] C=5, gamma=0.0005 ...............................................
[CV] .

[CV] ...... C=50, gamma=0.001, score=0.8235294117647058, total=   0.0s
[CV] C=50, gamma=0.005 ...............................................
[CV] ...... C=50, gamma=0.005, score=0.7987012987012987, total=   0.0s
[CV] C=50, gamma=0.005 ...............................................
[CV] ...... C=50, gamma=0.005, score=0.8496732026143791, total=   0.0s
[CV] C=50, gamma=0.005 ...............................................
[CV] ...... C=50, gamma=0.005, score=0.8235294117647058, total=   0.0s
[CV] C=50, gamma=0.01 ................................................
[CV] ....... C=50, gamma=0.01, score=0.7987012987012987, total=   0.0s
[CV] C=50, gamma=0.01 ................................................
[CV] ....... C=50, gamma=0.01, score=0.8496732026143791, total=   0.0s
[CV] C=50, gamma=0.01 ................................................
[CV] ........ C=50, gamma=0.01, score=0.803921568627451, total=   0.0s
[CV] C=50, gamma=0.05 ................................................
[CV] .

[Parallel(n_jobs=1)]: Done  96 out of  96 | elapsed:    0.9s finished


GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [1, 5, 10, 50], 'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring=None, verbose=3)

In [7]:
# WARNING! BOILERPLATE CODE HERE!
# Plot the decision boundaries
# x_min = X[:, 0].min()
# x_max = X[:, 0].max()
# y_min = X[:, 1].min()
# y_max = X[:, 1].max()

# XX, YY = np.mgrid[x_min:x_max, y_min:y_max]
# Z = SVCmodel.decision_function(np.c_[XX.ravel(), YY.ravel()])

# # Put the result into a color plot
# Z = Z.reshape(XX.shape)
# # plt.pcolormesh(XX, YY, Z > 0, cmap=plt.cm.Paired)
# plt.contour(XX, YY, Z, colors=['k', 'k', 'k'],
#             linestyles=['--', '-', '--'], levels=[-.5, 0, .5])
# plt.scatter(X[:, 0], X[:, 1], c=y, cmap='bwr', edgecolor='k', s=100)
# plt.show()

Validation

In [8]:
X_train_scaled

array([[-1.40276225, -0.7578363 ,  0.51693097, ...,  0.29869263,
         0.4518722 , -1.19587205],
       [ 0.71287918, -0.7578363 ,  0.51693097, ..., -2.35720832,
         0.4518722 ,  1.33332861],
       [ 0.71287918,  1.20613383,  0.51693097, ...,  0.29869263,
         0.4518722 ,  0.06872828],
       ...,
       [-1.40276225,  0.22414876,  0.51693097, ...,  0.29869263,
         0.4518722 ,  0.06872828],
       [-1.40276225, -0.7578363 ,  0.51693097, ...,  0.29869263,
        -2.21301511, -1.19587205],
       [-1.40276225,  0.22414876,  0.51693097, ...,  0.29869263,
         0.4518722 , -1.19587205]])

In [9]:
y_train_categorical

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.

In [10]:
predictions = grid.predict(X_test_scaled)
predictions  # (See the y_test length above. It matches with number of predictions below as its supposed to be.)

array([0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=int64)

In [11]:
# # Plot the decision boundaries
# x_min = X[:, 0].min()
# x_max = X[:, 0].max()
# y_min = X[:, 1].min()
# y_max = X[:, 1].max()

# XX, YY = np.mgrid[x_min:x_max, y_min:y_max]
# Z = SVMmodel.decision_function(np.c_[XX.ravel(), YY.ravel()])

# # Put the result into a color plot
# Z = Z.reshape(XX.shape)
# # plt.pcolormesh(XX, YY, Z > 0, cmap=plt.cm.Paired)
# plt.contour(XX, YY, Z, colors=['k', 'k', 'k'],
#             linestyles=['--', '-', '--'], levels=[-.5, 0, .5])
# plt.scatter(X[:, 0], X[:, 1], c=y, cmap='bwr', edgecolor='k', s=100)
# plt.show()

In [12]:
#              # of true positives (# of items correctly labeled as belonging to the +ve class) 
# precision = --------------------------------------------------------------------------------
#              # of items labeled as belonging to +ve class (i.e. true positives + false positives)

# (False positives are items incorrectly labeled as belonging to +ve class).

#            # of true positives 
# Recall =  ---------------------
            # of items actually belong to +ve class (i.e. true positives + false negatives) 
    
# (false negatives are items which were not labeled as belonging to the positive class but should have been).

# Calculate classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions,
                            target_names=["Not Approved", "Approved"]))

              precision    recall  f1-score   support

Not Approved       1.00      0.50      0.67        48
    Approved       0.82      1.00      0.90       106

 avg / total       0.87      0.84      0.83       154



In [13]:
joblib.dump(X_scaler, "SVM_Model_Sigmoid_X_scaler.pkl")

['SVM_Model_Sigmoid_X_scaler.pkl']

In [14]:
joblib.dump(grid, 'SVM_Model_Sigmoid.pkl')

['SVM_Model_Sigmoid.pkl']